<Project Sdk="Aspire.AppHost.Sdk/13.5.2">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>6d9f3892-e23e-4949-9356-f3831150e2f4</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.JavaScript" />
    <PackageReference Include="Aspire.Hosting.MongoDB" />
    <PackageReference Include="Aspire.Hosting.SqlServer" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Gateway\MC.Gateway\MC.Gateway.csproj" />
    <ProjectReference Include="..\..\Services\Delivering\MC.Delivering.API\MC.Delivering.API.csproj" />
    <ProjectReference Include="..\..\Services\Financial\MC.Financial.API\MC.Financial.API.csproj" />
    <ProjectReference Include="..\..\Services\Interaction\MC.Interaction.API\MC.Interaction.API.csproj" />
    <ProjectReference Include="..\..\Services\Notifications\MC.Notifications.API\MC.Notifications.API.csproj" />
    <ProjectReference Include="..\..\Services\Ordering\MC.Ordering.API\MC.Ordering.API.csproj" />
    <ProjectReference Include="..\..\Services\Catalog\MC.Catalog.API\MC.Catalog.API.csproj" />
    <ProjectReference Include="..\..\Services\Profiles\MC.Profiles.API\MC.Profiles.API.csproj" />
    <ProjectReference Include="..\..\Services\Promotion\MC.Promotion.API\MC.Promotion.API.csproj" />
    <ProjectReference Include="..\..\Services\Shopping\MC.Shopping.API\MC.Shopping.API.csproj" />
    <ProjectReference Include="..\..\Services\Statistics\MC.Statistics.API\MC.Statistics.API.csproj" />
  </ItemGroup>

</Project>
