<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
	<FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
	<PackageReference Include="Auth0.AspNetCore.Authentication.Api" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MC.Shared.Application\MC.Shared.Application.csproj" />
    <ProjectReference Include="..\MC.Shared.Infrastructure\MC.Shared.Infrastructure.csproj" />
  </ItemGroup>

</Project>
