<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.SqlServer" />
    <PackageReference Include="Aspire.Hosting.Testing" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit.v3.mtp-off" />
    <PackageReference Include="xunit.runner.visualstudio">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\Services\Profiles\MC.Profiles.API\MC.Profiles.API.csproj" />
    <ProjectReference Include="..\..\..\Aspire\AspireApp.AppHost\AspireApp.AppHost.csproj">
      <IsAspireProjectResource>false</IsAspireProjectResource>
    </ProjectReference>
  </ItemGroup>
</Project>
